---

# Role to create the management accounts to progress the ROSA cluster creation.

- name: Clear variables
  set_fact:
    opRoles: []
    create_op_roles: False
    create_oidc_provider: False

- name: Query for operator role existence
  shell: |
    set timeout 300

    {{rosa_path}}rosa describe cluster --cluster {{cluster_name}}

    exit 0
  args:
    executable: /bin/bash
  delegate_to: localhost
  register: response

- fail:
    msg: "Cluster {{cluster_name}} does not exist."
  when: '"E: Failed to get cluster" in response'

- name: Parse response for operator roles
  set_fact:
    opRoles: "{{opRoles + [{'Name':item[0],'Exists':True}]}}"
  when: item[0] in item[1]
  with_nested:
    - "{{operator_roles}}"
    - "{{response.stdout}}"

- name: Review to determine if need to create operator roles
  set_fact:
    create_op_roles: True
  when: not item.Exists
  loop: "{{opRoles}}"

- name: Create operator roles
  shell: |
    set timeout 300

    {{rosa_path}}rosa create operator-roles -y \
    --mode auto \
    --profile {{profile}} \
    --cluster {{cluster_name}}

    exit 0
  args:
    executable: /bin/bash
  delegate_to: localhost
  when: create_op_roles

- name: Check for OIDC role existence
  debug:
    msg: "This will check for the OIDC role"

- name: Create OIDC Provider role
  shell: |
    set timeout 300

    {{rosa_path}}rosa create oidc-provider -y \
    --mode auto \
    --profile {{profile}} \
    --cluster {{cluster_name}}

    exit 0
  args:
    executable: /bin/bash
  delegate_to: localhost
  when: create_oidc_provider