---
####

# Returns subnet CIDRs for a VPC consisting of public and private tiers (refer archtiecture documentation)

- name: Add VPC CIDR Fact to Inventory or use existing
  set_fact:
    inventory: "{{inventory | combine({'edge':{'cidrs':{'vpc':vpcCIDR}}}, recursive=True)}}"
  vars:
    vpcCIDR: "{{inventory.edge.cidrs.vpc if(inventory.edge.cidrs.vpc is defined) else vpc_cidr}}"

# Calculate the edge subnets
- name: Split VPC CIDR into ACL subnets
  script: ../files/split-subnet.py --cidr {{inventory.edge.cidrs.vpc}} --prefix {{tierPrefix}} --count 2 
  register: cidrReturn
  failed_when:
  - cidrReturn.stdout_lines | length < 2

- name: Add public CIDR information to inventory
  set_fact:
    inventory: "{{inventory | combine({'edge': {'cidrs': {'public': {'cidr': cidrReturn.stdout_lines[0]}}}}, recursive=True)}}"

- name: Add private CIDR information to inventory
  set_fact:
    inventory: "{{inventory | combine({'edge': {'cidrs': {'private': {'cidr': cidrReturn.stdout_lines[1]}}}}, recursive=True)}}"

- name: Split public subnet into subnets by availability zone
  script: ../files/split-subnet.py --cidr {{inventory.edge.cidrs.public.cidr}} --prefix {{subnetPrefix}} --count {{inventory.availability_zones | length}}
  register: cidrReturn
  failed_when:
  - cidrReturn.stdout_lines | length < inventory.availability_zones | length

- name: Add public subnet CIDRs to inventory
  set_fact:
    inventory: "{{inventory | combine({'edge': {'cidrs': {'public': {'subnets':cidrReturn.stdout_lines}}}}, recursive=True) }}"

- name: Split private subnet into subnets by availability zone
  script: ../files/split-subnet.py --cidr {{inventory.edge.cidrs.private.cidr}} --prefix {{subnetPrefix}} --count {{inventory.availability_zones | length}}
  register: cidrReturn
  failed_when:
  - cidrReturn.stdout_lines | length < inventory.availability_zones | length

- name: Add private subnet CIDRs to inventory
  set_fact:
    inventory: "{{inventory | combine({'edge': {'cidrs': {'private': {'subnets':cidrReturn.stdout_lines}}}}, recursive=True) }}"