---

- name: Determine if using default region
  set_fact:
    defaultRegion: True
  when: (reqRegion is not defined) or (reqRegion|length == 0)

- name: Determine if using specified region
  set_fact:
    defaultRegion: False
  when: (reqRegion is defined) and (reqRegion|length > 0)

- name: Create AWS NAT Gateway with specified region
  amazon.aws.ec2_vpc_nat_gateway:
    subnet_id: "{{subnetId}}"
    region: "{{reqRegion}}"
    profile: "{{usrProfile}}"
    wait: "{{wait_for_complete}}"
    tags:
      Name: "{{ngwName}}"
      Resource: "{{envName}}"
  register: returnedInfo_region
  when: not defaultRegion

- name: Create AWS NAT Gateway with default region
  amazon.aws.ec2_vpc_nat_gateway:
    subnet_id: "{{subnetId}}"
    profile: "{{usrProfile}}"
    wait: "{{wait_for_complete}}"
    tags:
      Name: "{{ngwName}}"
      Resource: "{{envName}}"
  register: returnedInfo_default
  when: defaultRegion

- name: Set igwReturnedInfo to default if using default region
  set_fact:
    ngwReturnedInfo: "{{returnedInfo_default}}"
  when: defaultRegion

- name: Set igwReturnedInfo to specified if using specified region
  set_fact:
    ngwReturnedInfo: "{{returnedInfo_region}}"
  when: not defaultRegion