---
# These are the default values if none if provided
rosa_path: "/usr/local/bin/"
aws_config_path: "~/.aws/"
profile: "default"
wait_for_completion: True    # This will cause the playbook to wait for the cluster to complete being built before proceeding
check_for_existence: True    # This will cause the playbook to check for the existence of cluster_name before proceeding
multi_az: False     # Create a ROSA cluster across multiple availabilty zones
new_vpc: True       # Create ROSA cluster in a new VPC if set true, otherwise, use an existing cluster
machine_cidr: 10.0.0.0/24
service_cidr: 172.30.0.0/16
pod_cidr: 10.128.0.0/14
version: 4.9.21
host_prefix: 23
no_retries: 30      # Number of retries when waiting for completion
retry_delay: 120    # Delay between retries when waiting for competion
ready_state: "ready"