---

- name: Query AWS for Client VPN details
  shell: |
    set timeout 300

    {{aws_path}}aws ec2 describe-client-vpn-endpoints \
    --filters Name=vpc-id,Values={{vpcId}}

    exit 0
  args:
    executable: /bin/bash
  delegate_to: localhost
  register: response