---

# This role validates the prerequisites for the rest of the installation

# Valdiate ROSA API Access
- name: Verify ROSA API access and configuration
  include_tasks:  validate-access.yaml
  vars:
    profile: "{{inventory.profile}}"
    region: "{{inventory.region}}"
  when: (inventory.rosa_validation.access is not defined) or (inventory.rosa_validation.access != 'pass')

- name: Verify account roles
  include_tasks: validate-roles.yaml
  when: (inventory.rosa_validation.roles is not defined) or (inventory.rosa_validation.roles != 'pass')

# To do - add validation of quota and permissions