---

# This role validates the prerequisites for the rest of the installation

# Valdiate ROSA API Access
- name: Verify ROSA API access and configuration
  include_tasks:  validate-access.yaml
  vars:
    profile: "{{inventory.profile}}"
    region: "{{inventory.region}}"

- name: Verify account roles
  include_tasks: validate-roles.yaml

# To do - add validation of quota and permissions