---

# This role validates the prerequisites for the rest of the installation

# Valdiate ROSA API Access
- name: Verify ROSA API access and configuration
  import_role:
    name: rosa_validate_access
  vars:
    profile: "{{awsProfile}}"
    region: "{{awsRegion}}"

- name: Verify account roles
  import_role:
    name: rosa_validate_roles

# To do - add validation of quota and permissions