---

- name: Clear variables
  set_fact:
    cluster: []
    response: []

- name: Query for ROSA Cluster existence
  shell: |
    set timeout 300

    {{rosa_path}}rosa create cluster

    exit 0
  args:
    executable: /bin/bash
  delegate_to: localhost
  register: response