---

- name: Get the current time
  command: date
  register: dateResponse

- name: Record current date
  set_fact:
    end_time: "{{dateResponse.stdout_lines[0]}}"

- debug: 
    msg: [
      "Start time was {{start_time}}",
      "End time was {{end_time}}"    
    ]