---

# Create CIDR info if required
- name: Determine workload CIDR requirements
  include_tasks: wkld-cidr.yaml
  when: >
    (inventory.wkld.cidrs is defined) and
    ((inventory.wkld.cidrs.private is not defined) or
    (inventory.wkld.cidrs.public is not defined))

# Create VPC if required
- name: Build Workload VPC if not already present
  include_tasks: wkld-vpc.yaml
  when: (inventory.wkld.vpc is defined) and (inventory.wkld.vpc | length == 0)

# Create subnets if required
- name: Create workload public subnets
  include_tasks: wkld-subnets.yaml
  when: (inventory.wkld.subnets is defined) and (inventory.wkld.subnets | length == 0)

# Create VPC Endpoint for S3 service
- name: Create VPC Endpoint for S3 service
  include_tasks: wkld-vpce.yaml
  when: (inventory.wkld.vpce is defined) and (inventory.wkld.vpce | length == 0)

