---

- name: Set parameters for edge to management
  set_fact:
    pcxList: "{{pcxList | default([]) + [{'Name': name, 'vpc1':vpc1, 'vpc2':vpc2}]}}"
  vars:
    name: "{{resourceGroup|lower}}-{{edge|lower}}-{{management|lower}}-pcx"
    vpc1: "{{resourceGroup|lower}}-{{edge|lower}}"
    vpc2: "{{resourceGroup|lower}}-{{management|lower}}"

- name: Create VPC Peer Connection Edge to Management
  include_role:
    name: create_pcx
  vars:
    pcxName: "{{pcxList[0].Name}}"
    vpc1Prefix: "{{pcxList[0].vpc1}}"
    vpc2Prefix: "{{pcxList[0].vpc2}}"

- name: Amend pcxId to list for vpc1
  set_fact:
    pcxList: "{{pcxList | map('combine',{'pcxId': peering_id})}}"
  with_list: "{{pcxList}}"

- name: Set parameters for edge to workload
  set_fact:
    pcxList1: "{{pcxList1 | default([]) + [{'Name': name, 'vpc1':vpc1, 'vpc2':vpc2}]}}"
  vars:
    name: "{{resourceGroup|lower}}-{{edge|lower}}-{{workload|lower}}-pcx"
    vpc1: "{{resourceGroup|lower}}-{{edge|lower}}"
    vpc2: "{{resourceGroup|lower}}-{{workload|lower}}"

- name: Create VPC Peer Connection Edge to Management
  include_role:
    name: create_pcx
  vars:
    pcxName: "{{pcxList1[0].Name}}"
    vpc1Prefix: "{{pcxList1[0].vpc1}}"
    vpc2Prefix: "{{pcxList1[0].vpc2}}"

- name: Add pcxId to second entry
  set_fact:
    pcxList1: "{{pcxList1 | map('combine',{'pcxId': peering_id})}}"

- set_fact:
    pcxList: "{{pcxList + pcxList1}}"

- debug:
    msg: "{{mgmt_pcx}}"
  vars: 
    mgmt_pcx: "{{pcxList | json_query(mgmtQuery)}}"
    mgmtQuery: "[?starts_with(Name,'{{resourceGroup|lower}}-{{edge|lower}}-{{management|lower}}')].pcxId"
