---

# Create the transit gateway
- name: Create the transit gateway
  include_tasks: tgw.yaml
  when: (inventory.tgw is defined) and (inventory.tgw | length == 0)

# Create transit gateway attachment to edge VPC

# Create transit gateway attachement to mgmt VPC

# Create transit gateway attachment to wkld VPC

# Create edge VPC route tables

# Create mgmt VPC route tables

# Create wkld VPC route tables
  
