---

# Create peering connection between edge and management VPC 

- name: Set parameters for edge to management
  set_fact:
    inventory: "{{inventory | combine( {'pcxs':{'edge_mgmt':{'name': name, 'vpc1':vpc1, 'vpc2':vpc2}}}, recursive=True ) }}"
  vars:
    name: "{{resourceGroup|lower}}-{{edge|lower}}-{{management|lower}}-pcx"
    vpc1: "{{inventory.edge.vpc.name}}"
    vpc2: "{{inventory.mgmt.vpc.name}}"
  when: (inventory.pcxs.edge_mgmt is defined)

- name: Create VPC Peer Connection Edge to Management
  include_role:
    name: create_pcx
  vars:
    pcxName: "{{inventory.pcxs.edge_mgmt.name}}"
    vpc1Name: "{{inventory.edge.vpc.name}}"
    vpc2Name: "{{inventory.mgmt.vpc.name}}"
    envName: "{{resourceGroup|lower}}"
  when: (inventory.pcxs.edge_mgmt is defined)

- name: Amend pcxId to list for vpc1
  set_fact:
    inventory: "{{inventory | combine({'pcxs':{'edge_mgmt':{'id': peering_id}}}, recursive=True)}}"
  when: (inventory.pcxs.edge_mgmt is defined)


# Create peering connection between edge and workload VPC 

- name: Set parameters for edge to workload
  set_fact:
    inventory: "{{inventory | combine( {'pcxs':{'edge_wkld':{'name': name, 'vpc1':vpc1, 'vpc2':vpc2}}}, recursive=True ) }}"
  vars:
    name: "{{resourceGroup|lower}}-{{edge|lower}}-{{workload|lower}}-pcx"
    vpc1: "{{inventory.edge.vpc.name}}"
    vpc2: "{{inventory.wkld.vpc.name}}"
  when: (inventory.pcxs.edge_wkld is defined)

- name: Create VPC Peer Connection Edge to Workload
  include_role:
    name: create_pcx
  vars:
    pcxName: "{{inventory.pcxs.edge_wkld.name}}"
    vpc1Name: "{{inventory.edge.vpc.name}}"
    vpc2Name: "{{inventory.wkld.vpc.name}}"
    envName: "{{resourceGroup|lower}}"
  when: (inventory.pcxs.edge_wkld is defined)

- name: Add pcxId to second entry
  set_fact:
    inventory: "{{inventory | combine({'pcxs':{'edge_wkld':{'id': peering_id}}}, recursive=True)}}"
  when: (inventory.pcxs.edge_wkld is defined)
