---

- name: Get edge subnet details if missing
  amazon.aws.ec2_vpc_subnet_info:
    profile: "{{awsProfile|default(omit)}}"
    region: "{{awsRegion|default(omit)}}"
    filters: 
      vpc-id: "{{vpc_id}}"
      "tag:Resource": "{{resource}}"
  register: returnedInfo

- name: Fail if no subnets found
  fail:
    msg: "ERROR: No subnets found in VPC {{vpc_id}}"
  when: returnedInfo.subnets | length == 0

- name: Parse returned info into inventory fact
  set_fact:
    subnets: "{{subnets | default([]) + [{'name':subnet_name,'avialability_zone':az, 'cidr':cidr, 'id':subnet_id, 'state':state}] }}"
  vars:
    subnet_name: "{{item.tags.Name}}"
    az: "{{item.availability_zone}}"
    cidr: "{{item.cidr_block}}"
    subnet_id: "{{item.id}}"
    state: "{{item.state}}"
  loop: "{{returnedInfo.subnets}}"
  loop_control:
    label: "{{item.id}}"

- name: Update inventory
  set_fact:
    inventory: "{{inventory | combine({vpc:{'subnets':subnets}}, recursive=True) }}"
    