---

# Pass a dictionary, cluster, to this role. Cluster needs to contain,
# Name
# Region
# Compute nodes
# Multi-AZ - boolean. True to create a multi-AZ cluster. Defaults to false.
# Subnets - list of existing subnet id's if deploying to an existing cluster


# Kick off cluster creation

- name: Clear variables
  set_fact:
    response: []
    cluster_exists: "{{False if (not check_for_existence) else None}}"   # Assume cluster does not exist if told not to check

- name: Query list of ROSA Clusters
  shell: |
    set timeout 300

    {{rosa_path}}rosa list clusters

    exit 0
  args:
    executable: /bin/bash
  delegate_to: localhost
  register: response
  when: check_for_existence

- name: Parse response for existing cluster
  set_fact: 
    cluster_exists: "{{True if (cluster_name in response.stdout) else False}}"
  when: check_for_existence

- name: Get AWS Account Details
  amazon.aws.aws_caller_info:
  register: accountResponse
  when: (accountid is not defined) and (not cluster_exists)

- name: Set account id
  set_fact:
    accountid: "{{accountResponse.account}}"
  when: (accountid is not defined) and (not cluster_exists)

- name: Set region to default if not specified
  set_fact:
    region: "{{ lookup('file', aws_config_path+'config') | regex_search('region = (.+)', '\\1') | first }}"
  when: (region is not defined) and (not cluster_exists)

- name: Determine if multi-az for existing VPC deployment
  set_fact:
    multi_az: "{{True if(subnets|length>2) else False}}"
  when: not new_vpc

- name: Set default compute nodes if not provided
  set_fact:
    compute_nodes: "{{3 if(multi_az) else 2}}"
  when: compute_nodes is not defined

- name: Kick off multi-availability zone cluster creation in new VPC
  include_tasks:
    file: new-multi-az.yaml
  when: (new_vpc) and (multi_az) and (not cluster_exists) and (not privatelink)

- name: Kick off single availability zone cluster creation in new VPC
  include_tasks:
    file: new-single-az.yaml
  when: (new_vpc) and (not multi_az) and (not cluster_exists) and (not privatelink)

- name: Kick off multi-availability zone cluster creation in existing VPC
  include_tasks:
    file: multi-az.yaml
  when: (not new_vpc) and (multi_az) and (not cluster_exists) and (not privatelink)

- name: Kick off single availability zone cluster creation in existing VPC
  include_tasks:
    file: single-az.yaml
  when: (not new_vpc) and (not multi_az) and (not cluster_exists) and (not privatelink)

- name: Kick off multi-availability zone cluster creation in existing VPC with PrivateLink
  include_tasks:
    file: pl-multi-az.yaml
  when: (not new_vpc) and (multi_az) and (not cluster_exists) and (privatelink)

- name: Kick off single availability zone cluster creation in existing VPC with PrivateLink
  include_tasks:
    file: pl-single-az.yaml
  when: (not new_vpc) and (not multi_az) and (not cluster_exists) and (privatelink)

- name: Create management roles
  include_tasks:
    file: role_creation.yaml
  when: not cluster_exists

- name: Wait for cluster completion
  include_tasks:
    file: wait.yaml
  when: wait_for_completion and not cluster_exists



