---


- name: Determine if using default region
  set_fact:
    defaultRegion: True
  when: (reqRegion is not defined) or (reqRegion|length == 0) 

- name: Determine if using specified region
  set_fact:
    defaultRegion: False
  when: (reqRegion is defined) and (reqRegion|length > 0) 

- name: Create VPC with specified region
  amazon.aws.ec2_vpc_net:
    name: "{{envName}}-{{vpcName}}-vpc"
    cidr_block: "{{cidr_block}}"
    region: "{{reqRegion}}"
    profile: "{{usrProfile}}"
    tags:
      environment: "{{envName}}"
    tenancy: default
  register: returnedInfo_region
  tags: vpc
  when: not defaultRegion

- name: Create VPC using profile default region
  amazon.aws.ec2_vpc_net:
    name: "{{envName}}-{{vpcName}}-vpc"
    cidr_block: "{{cidr_block}}"
    profile: "{{usrProfile}}"
    tags:
      environment: "{{envName}}"
    tenancy: default
  register: returnedInfo_default
  tags: vpc
  when: defaultRegion

- name: Set vpcData to default set if using default region
  set_fact:
    vpcData: "{{returnedInfo_default}}"
  when: defaultRegion

- name: Set vpcData to specified set if using specified region
  set_fact:
    vpcData: "{{returnedInfo_region}}"
  when: not defaultRegion
