---

# Create CIDR info if required
- name: Determine management CIDR requirements
  include_tasks: edge-cidr.yaml
  when: >
    (inventory.edge.cidrs is defined) and
    ((inventory.edge.cidrs.ingress is not defined) or
    (inventory.edge.cidrs.egress is not defined) or
    (inventory.edge.cidrs.bastion is not defined))

# Create VPC if required
- name: Build VPC if not already present
  include_tasks: edge-vpc.yaml
  when: (inventory.edge.vpc is defined) and (inventory.edge.vpc | length == 0)

# Create subnets if required
- name: Create ingress, egress and bastion subnets
  include_tasks: edge-subnets.yaml
  when: (inventory.edge.subnets is defined) and (inventory.edge.subnets | length == 0)

# Create internet gateway if required
- name: Create Internet Gateway
  include_tasks: edge-igw.yaml
  when: >
    (inventory.edge.igw is defined) and (inventory.edge.igw | length == 0)

# Create NAT Gateway if required
- name: Create NAT Gateways for public subnets
  include_tasks: edge-ngw.yaml
  when: (inventory.edge.ngw is defined) and (inventory.edge.ngw | length == 0)

# Add security group defaults
