---

###
# Create the internet gateway

- name: Create the internet gateway
  import_role:
    name: create_igw
  vars:
    vpcId: "{{ inventory.edge.vpc.id }}"
    igwName: "{{ resourceGroup | lower }}-{{ edge | lower }}-igw"
    usrProfile: "{{ awsProfile }}"
    reqRegion: "{{ awsRegion }}"
    envName: "{{ resourceGroup|lower }}"

- name: Update inventory data with gateway details
  set_fact:
    inventory: "{{inventory | combine({'edge':{'igw':igwDetails}}, recursive=True)}}"
  vars:
    igwDetails: 
      name: "{{ resourceGroup | lower }}-{{ edge | lower }}-igw"
      id: "{{igwData.internet_gateway_id}}"
