---

# Create CIDR info if required
- name: Determine management CIDR requirements
  include_tasks: std-cidr.yaml
  when: (inventory.cidrs | length == 0)

# Create VPC if required
- name: Build VPC if not already present
  include_tasks: std-vpc.yaml
  when: (inventory.vpc is defined) and (inventory.vpc | length == 0)

# Create subnets if required
- name: Create public and private subnets
  include_tasks: std-subnets.yaml
  when: (inventory.subnets is defined) and (inventory.subnets | length == 0)

# Create internet gateway if required
- name: Create Internet Gateway
  include_tasks: std-igw.yaml
  when: >
    (inventory.igw is defined) and (inventory.igw | length == 0)

# Create NAT Gateway if required
- name: Create NAT Gateways for public subnets
  include_tasks: std-ngw.yaml
  when: (inventory.ngw is defined) and (inventory.ngw | length == 0)

# Create Route tables if required
- name: Create Route Tables
  include_tasks: std-rtbs.yaml
  when: (inventory.rtbs is defined) and (inventory.rtbs | length == 0)

# Create VPC Endpoint for S3 service
- name: Create VPC Endpoint for S3 service
  include_tasks: std-vpce.yaml
  when: (inventory.vpce is defined) and (inventory.vpce | length == 0)

# Create the ROSA Cluster if required
- name: Create the ROSA cluster
  include_tasks: std-rosa.yaml
  when: (inventory.rosa is defined) and (inventory.rosa | length == 0)

# Create private subnets for EC2 instances
- name: Create ec2 private subnets
  include_tasks: std-ec2-subnets.yaml
  when: (inventory.ec2_subnets is defined) and (inventory.ec2_subnets | length == 0)

# Create route tables for EC2 private subnets
- name: Create ec2 private subnet route tables
  include_tasks: std-ec2-rtbs.yaml
  when: (inventory.ec2_rtbs is defined) and (inventory.ec2_rtbs | length == 0)

# Lock down environment with Network ACL
- name: Create the Network ACL for the private and ec2 subnets
  include_tasks: std-nacl.yaml
  when: (inventory.nacl is defined) and (inventory.nacl | length == 0)