---

# Get facts of AWS environment using AWS collection for Ansible

-   name: Get and display VPC details
    hosts: localhost
    gather_facts: false
    vars:
        vpcName: "fs-cloud-edge-vpc"
    tasks:

# Gather facts about VPC with tag Name and Value
    -   name: check vpc presence
        amazon.aws.ec2_vpc_net_info:
            filters:
                "tag:Name": "{{ vpcName }}"
        register: my_vpcs
        delegate_to: localhost
    
    - debug: 
        msg: "Edge VPC id is {{my_vpcs}}"