---
  - name: ReadJsonfile
    hosts: localhost
    tasks:
      - name: Display the JSON file content
        shell: cat ../variables.json
        register: result

      - name: Save JSON data to variables as Fact
        set_fact:
          jsondata: "{{ result.stdout | from_json }}"

      - name: Get list of VPC names
        set_fact:
          vpcnames: "{{ jsondata | json_query(jmesquery) }}"
        vars:
          jmesquery: 'vpcs[*].name'

      - name: Get region
        set_fact:
          awsregion: "{{ jsondata | json_query(jmesquery) }}"
        vars:
          jmesquery: 'region.name'

      - name: Display AWS region
        debug: 
          msg : " AWS Region = {{ awsregion }} "

      - name: List of VPCs to create
        debug: 
          msg: "{{ item }}"
        with_items:
          - "{{ vpcnames }}"

