---

  # Test playbook for reading json files
  
  - name: Read JSON File
    hosts: localhost
    tasks:
      - name: Read the JSON file content
        shell: cat ../variables.json
        register: jsoncontent

      - name: Save JSON data to variables as Fact
        no_log: True
        set_fact:
          jsondata: "{{ jsoncontent.stdout | from_json }}"

      - name: Get region
        no_log: True
        set_fact:
          awsregion: "{{ jsondata | json_query(jmesquery) }}"
        vars:
          jmesquery: 'region.name'

      - name: Display Region to be utilized
        debug:
          msg: ' AWS Region = {{ awsregion }} '

      - name: Read VPCs to be created
        set_fact:
          vpclist: "{{ vpcs|default({}) | combine ( {item.name : item.usage} ) }}"
        with_items: "{{ jsondata | json_query('[*]') }}"

      - name: Display VPCs
        debug: var=vpclist

      # Following just displays the output without saving as a variable
      #- name: List of VPCs to create
      #  debug: msg="{{ jsondata | json_query(jmesquery) }}"
      #  vars:
      #    jmesquery: 'vpcs[*].name'

      #- name: VPCs to be created by type
      #  debug: msg="{{ jsondata | json_query(jmesquery) }}"
      #  vars:
      #    jmesquery: 'vpcs[*].name'

