---

- hosts: localhost
  roles:
    - edge_cidrs
    - edge_vpc
    - edge_subnets
    - edge_igw
    - edge_nat
    - edge_nacl

    # Routes need to be created after all VPCs and network devices
    - edge_routes
    