# Output of VPC query for testing

-   cidr_block: 10.200.0.0/16
        cidr_block_association_set:
        -   association_id: vpc-cidr-assoc-02893dd68d57b66d3
            cidr_block: 10.200.0.0/16
            cidr_block_state:
                state: associated
        classic_link_dns_supported: false
        classic_link_enabled: false
        dhcp_options_id: dopt-d97279be
        enable_dns_hostnames: false
        enable_dns_support: true
        id: vpc-0e55f137c47732495
        instance_tenancy: default
        is_default: false
        owner_id: 005990573564
        state: available
        tags:
            Name: recloud-wkld-vpc
            Resource: recloud
        vpc_id: vpc-0e55f137c47732495
    -   cidr_block: 10.0.0.0/16
        cidr_block_association_set:
        -   association_id: vpc-cidr-assoc-0703954ca2dc50541
            cidr_block: 10.0.0.0/16
            cidr_block_state:
                state: associated
        -   association_id: vpc-cidr-assoc-0bd1d0c86e851cb16
            cidr_block: 10.1.0.0/16
            cidr_block_state:
                state: associated
        -   association_id: vpc-cidr-assoc-01def8633f8673c66
            cidr_block: 10.2.0.0/16
            cidr_block_state:
                state: associated
        classic_link_dns_supported: false
        classic_link_enabled: false
        dhcp_options_id: dopt-d97279be
        enable_dns_hostnames: true
        enable_dns_support: true
        id: vpc-0720ebfb9b1397a75
        instance_tenancy: default
        is_default: false
        owner_id: 005990573564
        state: available
        tags:
            Name: recloud-edge-vpc
            Resource: recloud
        vpc_id: vpc-0720ebfb9b1397a75
    -   cidr_block: 10.100.0.0/16
        cidr_block_association_set:
        -   association_id: vpc-cidr-assoc-0f581740deef6ce3d
            cidr_block: 10.100.0.0/16
            cidr_block_state:
                state: associated
        classic_link_dns_supported: false
        classic_link_enabled: false
        dhcp_options_id: dopt-d97279be
        enable_dns_hostnames: false
        enable_dns_support: true
        id: vpc-0b8b3e2694da71dd1
        instance_tenancy: default
        is_default: false
        owner_id: 005990573564
        state: available
        tags:
            Name: recloud-mgmt-vpc
            Resource: recloud
        vpc_id: vpc-0b8b3e2694da71dd1
