---

# Create CIDR info if required
- name: Determine management CIDR requirements
  include_tasks: mgmt-cidr.yaml
  when: >
    (inventory.mgmt.cidrs is defined) and
    ((inventory.mgmt.cidrs.private is not defined) or
    (inventory.mgmt.cidrs.public is not defined))

# Create VPC if required
- name: Build Management VPC if not already present
  include_tasks: mgmt-vpc.yaml
  when: (inventory.mgmt.vpc is defined) and (inventory.mgmt.vpc | length == 0)

# Create subnets if required
- name: Create management public subnets
  include_tasks: mgmt-subnets.yaml
  when: (inventory.mgmt.subnets is defined) and (inventory.mgmt.subnets | length == 0)

# Create VPC Endpoint for S3 service
- name: Create VPC Endpoint for S3 service
  include_tasks: mgmt-vpce.yaml
  when: (inventory.mgmt.vpce is defined) and (inventory.mgmt.vpce | length == 0)

