---

- name: Set VPC name
  set_fact:
    vpc_name: "{{inventory.resource}}-{{inventory.mgmt.identifier}}-vpc"

- name: Create management VPC
  import_role:
    name: create_vpc
  vars:
    # These variable are defined in the global_vars file
    envName: "{{inventory.resource}}"
    vpcName: "{{vpc_name}}"
    usrProfile: "{{inventory.profile}}"
    reqRegion: "{{inventory.region|default(omit)}}"
    # The cidr_block is obtained from the earlier subnet calcs - only create with private CIDR
    cidr_block: "{{inventory.mgmt.cidrs.vpc}}"

- name: Add VPC information to inventory
  set_fact:
    inventory: "{{inventory | combine({'mgmt':{'vpc':vpcDetails}}, recursive=True)}}"
  vars:
    vpcDetails: 
      name: "{{vpcData.tags.Name}}"
      cidr: "{{vpcData.cidr_block}}"
      id: "{{vpcData.id}}"
      state: "{{vpcData.state}}"