---

- name: Create IGW
  include_role:
    name: create_igw
  vars:
    igwName: "{{ resourceGroup | lower }}-{{ management | lower }}-igw"
    envName: "{{ resourceGroup | lower }}"
    vpcId: "{{ inventory.mgmt.vpc.id }}"
    reqRegion: "{{ awsRegion }}"
    usrProfile: "{{ awsProfile }}"


- name: Update inventory with IGW details
  set_fact:
    inventory: "{{inventory | combine({'mgmt':{'igw':igwDetails}}, recursive=True)}}"
  vars:
    igwDetails: 
      name: "{{ resourceGroup | lower }}-{{ management | lower }}-igw"
      id: "{{igwData.internet_gateway_id}}"
