---

- name: Add VPC CIDR Fact to Inventory or use existing
  set_fact:
    inventory: "{{inventory | combine({'mgmt':{'cidrs':{'vpc':vpcCIDR}}}, recursive=True)}}"
  vars:
    vpcCIDR: "{{inventory.mgmt.vpc.cidr if(inventory.mgmt.vpc.cidr is defined) else management_cidr}}"

- name: Split VPC CIDR into public and private CIDRs
  script: ../files/split-subnet.py --cidr {{inventory.mgmt.cidrs.vpc}} --prefix {{mgmtTierPrefix}} --count 2
  register: cidrReturn
  failed_when:
  - cidrReturn.stdout_lines | length < 2

- name: Add public CIDR to inventory
  set_fact:
    inventory: "{{inventory | combine({'mgmt':{'cidrs':{'public':{'cidr':cidrReturn.stdout_lines[0]}}}}, recursive=True) }}"

- name: Add private CIDR to inventory
  set_fact:
    inventory: "{{inventory | combine({'mgmt':{'cidrs':{'private':{'cidr':cidrReturn.stdout_lines[1]}}}}, recursive=True) }}"

- name: Split public CIDR into subnets
  script: ../files/split-subnet.py --cidr {{inventory.mgmt.cidrs.public.cidr}} --prefix {{mgmtSubnetPrefix}}  --count {{availZones | length}}
  register: cidrReturn
  failed_when:
  - cidrReturn.stdout_lines | length < availZones | length

- name: Add public subnet CIDRs to inventory
  set_fact:
    inventory: "{{inventory | combine({'mgmt':{'cidrs':{'public':{'subnets':cidrReturn.stdout_lines}}}}, recursive=True)}}"

- name: Split private CIDR into subnets
  script: ../files/split-subnet.py --cidr {{inventory.mgmt.cidrs.private.cidr}} --prefix {{mgmtSubnetPrefix}}  --count {{availZones | length}}
  register: cidrReturn
  failed_when:
  - cidrReturn.stdout_lines | length < availZones | length

- name: Add private subnet CIDRs to inventory
  set_fact:
    inventory: "{{inventory | combine({'mgmt':{'cidrs':{'private':{'subnets':cidrReturn.stdout_lines}}}}, recursive=True)}}"

- debug:
    msg: "{{inventory}}"
