---

# Confirm proceed with build
- name: Prompt to proceed
  pause:
    prompt: "Presss return to continue or Ctrl-C and then a to abort."

# Now start to create the network elements
- name: Create VPC
  amazon.aws.ec2_vpc_net:
    name: "{{envNamePrefix}}-{{edge}}-vpc"
    cidr_block: "{{azSubnets}}"
    region: "{{awsRegion}}"
    profile: "{{awsProfile}}"
    tags:
      environment: "{{envNamePrefix}}"
    tenancy: default
  register: edgeVpc
  tags: vpc

- name: Create security group
  debug:
    msg: "Will create a default security group"

- name: Create edge ingress subnet 1
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{edgeVpc.vpc.id}}"
    az: "{{availZone1}}"
    cidr: "{{ingressSubnets[0]}}"
    profile: "{{awsProfile}}"
    tags:
      environment: "{{envNamePrefix}}"
  register: edgeIngressSubnetaz1
  tags: subnet

- name: Create edge ingress subnet 2
  debug:
    msg: "Will now create Edge Subnet {{edge}}-ingress02 with cidr {{ingressSubnets[1]}} in AZ {{availZone2}}"

- name: Create edge ingress subnet 3
  debug:
    msg: "Will now create Edge Subnet {{edge}}-ingress03 with cidr {{ingressSubnets[2]}} in AZ {{availZone3}}"

- name: Create edge bastion subnet 1
  debug:
    msg: "Will now create Edge Subnet {{edge}}-bastion01 with cidr {{bastionSubnets[0]}} in AZ {{availZone1}}"

- name: Create edge bastion subnet 2
  debug:
    msg: "Will now create Edge Subnet {{edge}}-bastion02 with cidr {{bastionSubnets[1]}} in AZ {{availZone2}}"

- name: Create edge bastion subnet 3
  debug:
    msg: "Will now create Edge Subnet {{edge}}-bastion03 with cidr {{bastionSubnets[2]}} in AZ {{availZone3}}"

- name: Create edge egress subnet 1
  debug:
    msg: "Will now create Edge Subnet {{edge}}-egress01 with cidr {{egressSubnets[0]}} in AZ {{availZone1}}"

- name: Create edge egress subnet 2
  debug:
    msg: "Will now create Edge Subnet {{edge}}-egress02 with cidr {{egressSubnets[1]}}in AZ {{availZone2}}"

- name: Create edge egress subnet 3
  debug:
    msg: "Will now create Edge Subnet {{edge}}-egress03 with cidr {{egressSubnets[2]}} in AZ {{availZone3}}"

- name: Create route tables
  debug:
    msg: "Will create the route tables"